version: "3"

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword

      TZ: Europe/Paris
    volumes:
      - "mysql-data:/var/lib/mysql"

  web:
    build: ./webserver
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: mydb
      MYSQL_PORT: 3306
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

volumes:
  mysql-data:
