version: "3"

services:
  db:
    build: ./database
    ports:
      - "5000:5000"
    env_file:
      - .secrets.env

      TZ: Europe/Paris
    volumes:
      - "mysql-data:/var/lib/mysql"

  web:
    build: ./webserver
    ports:
      - "8080:8080"
    env_file:
      - ./secrets.env

volumes:
  mysql-data:
