version: "3"

services:
  db:
    build: ./database
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      TZ: Europe/Paris
    volumes:
      - "mysql-data:/var/lib/mysql"

  web:
    build: ./webserver
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: mydb
      MYSQL_PORT: 3306
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

volumes:
  mysql-data:
