name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Print secrets 
      run: |
          docker-compose build 
          docker-compose run \
          -e MYSQL_USER==${{ secrets.MYSQL_USER }} \
          -e MYSQL_PASSWORD==${{ secrets.MYSQL_PASSWORD }} \
          -e MYSQL_ROOT_PASSWORD==${{ secrets.MYSQL_ROOT_PASSWORD }} \
          database

          docker-compose run \
          -e MYSQL_USER==${{ secrets.MYSQL_USER }} \
          -e MYSQL_PASSWORD==${{ secrets.MYSQL_PASSWORD }} \
          -e MYSQL_ROOT_PASSWORD==${{ secrets.MYSQL_ROOT_PASSWORD }} \
          webserver
