name: Deploy on Pull

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create secrets.env
        run: |
          echo "MYSQL_HOST=db" > ./secrets.env
          echo "MYSQL_DATABASE=mydb" >> ./secrets.env
          echo "MYSQL_PORT=3306" >> ./secrets.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> ./secrets.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> ./secrets.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> ./secrets.env

      - name: Build and deploy Docker Compose
        run: docker-compose up -d

      - name: Clean up
        run: rm ./secrets.env
